doc: oma-pm
AOSC-Dev/oma pull request #263
Opened 2024-12-09 14:52 UTC by wxiwnd

2025-02-06 06:45 UTC, MingcongBai requested changes

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// The summary of all the apt operations in rust-apt
Remove "the"

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// Config for apt, See Document for `AptConfig`.
see documentation for `AptConfig`

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// The summary of all the apt operations in rust-apt
Add period point.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// The hash of packages that will be autoremoved.
The set of packages to be autoremoved.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// The hash of packages that have been selected.
The set of selected packages.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// A list of lists containing broken packages that have unmet dependencies.
A set of lists

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// The Tokio runtime used for asynchronous operations.
Is this necessary? If so, why not also for `conn`?

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +/// Represent the mode of filter.
Modes of the result filter.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +/// Represent the sort methods of summary.
Keys for sorting results in the summary view.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// Represent how many thread will be used in downloading
The number of threads to be used for downloads.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// The directory which stores downloaded files
Path to downloaded files/archives.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// The config for authorization
Configuration for repository authorization.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// `local_debs`: Path for local deb package files
Path to

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// `local_debs`: Path for local deb package files
deb packages (remove files)

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// `args`: Config for oma, See Document for `OmaAptArgs`
- Use full "Configuration"
- see documentation for `OmaAptArgs`

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// Whether dry-run or not.
Toggle for dry-run mode.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// `dry_run`: Whether dry-run or not
Toggle for dry-run mode

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +    /// `config`: Config for apt, See Document for `AptConfig`
Configuration for ... see documentation for `AptConfig`

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/apt.rs
> +/// Represent a broken package, including the name and reason.
Broken package, struct contains its name and cause for broken status.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/lib.rs
> +//! The oma-pm crate serves as the main library for oma,
Drop the part "serves as the main library for oma, providing" and replace with "provides."

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/lib.rs
> +//! 1. **PackageInfo**: Provides definitions of package information and handle them to `oma-apt`.
Package information to be handled by `oma-apt`.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/lib.rs
> +//! 2. **Progress**: Tracks the progress of package management operations.
Reports

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/lib.rs
> +//! 3. **Search Result**: Defines the structure and handling of search results.
Drop "Defines the."

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/lib.rs
> +//! NOTE: `oma-apt` is another fork of `rust-apt` maintained by AOSC-Dev
Add a comma before "maintained."

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/lib.rs
> +//! ## Re-exports
What does this mean?

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/lib.rs
> +//! - `AptErrors`: Error definitions from `oma_apt` crate.
oma-apt?

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/lib.rs
> +//! - `PkgCurrentState`: Current state definitions from `oma_apt` crate.
Current package management status  from `oma-apt`.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/lib.rs
> +//! - `PackageStatus`: Status definitions from the `search` module.
Package status

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/matches.rs
> +/// Represent the type of package search engine.
Please drop all "Represents" from this point on.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/matches.rs
> +/// Represent the type of package search engine.
Search engine to use.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/matches.rs
> +/// Represent the method of getting platform arch.
getting system architecture

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/matches.rs
> +    /// The summary of all the apt operations in rust-apt
Summary of all pending APT operations...

"apt" is only appropriate to represent the command, for the project/tool, use "APT."

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/matches.rs
> +    /// If true, filters the packages to only include candidated packages.
If true, filter and only display matching candidates (defaults to true).

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/matches.rs
> +    /// If true, display all the debug packages.
Use (defaults to x) to save some space.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/matches.rs
> +    ///If true, filters the packages to only include downloadable candidated packages.
filter and only display downloadable candidates.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/matches.rs
> +    /// The method used to determine the native arch.
Method to determine the native architecture.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/matches.rs
> +    /// The method used to determine the native arch.
Ditto above for parenthetical format.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/matches.rs
> +    /// Matches packages and versions based on the provided keywords.
against the search pattern

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/matches.rs
> +    /// Query package from given glob (without matching version)
Query package based on a given pattern (without matching version)

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/matches.rs
> +/// return whether this package has debug version or not.
Report whether a specified package provides a matching package for debug symbols.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/pkginfo.rs
> +    /// The name of the package.
All of the "The"s below are unnecessary.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/pkginfo.rs
> +    /// The size of the package after installation, in bytes.
(in bytes)

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/pkginfo.rs
> +    /// The size of the package download from the internet, in bytes.
Download size of the package (in bytes)

Not necessarily from the Internet

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/pkginfo.rs
> +    /// A map of dependencies for the package.
Dependency map for the package

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/pkginfo.rs
> +    /// A detailed description of the package.
Remove "A"

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/pkginfo.rs
> +    /// The APT sources from which the package can be downloaded.
will be downloaded

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/pkginfo.rs
> +    /// A brief description of the package.
Remove "A"

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +//! - IndiciumSearch
Some description will help.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +/// Represent the status of a package.
Status of the package.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +/// Represents an entry in the package search results.
Entry in the package search results.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +    /// The name of this package
Replace all "this" with "the."

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +    /// Whether this package has debug or not.
Whether the package provides a matching package for debug symbols.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +    /// Whether this package is a part of system base packages.
Whether the package is an AOSC OS metapackage (-base package).

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +/// Represents the result of a searching process.
Result of a search process.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +    /// A string contains the name of a package to search for.
Remove all "A" below. You should also be using present progressive tense.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +    /// A boolean indicating whether this package is a base package or not.
See my note about what "base" means above.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +    /// A boolean indicating whether this result has debug version or not.
has a matching package for debug symbols

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +    /// A `PackageStatus` instance which provides the status of the package.
which reports

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +    /// The Cache from oma-apt (rust-apt), which contains the summary of all the apt operations.
This is the locally cached index.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +    /// A map contains package names and their corresponding search entries.
Map of package names and their...

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +    /// The index used to perform search operations.
Index used to perform search operations.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +    /// * `query` - An optional string that holds the query to match the package name.
search query (or pattern).

The rest are not needed.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +    /// * `i` - A string that holds the name of the package to search.
containing the, drop "that"

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +    /// * `Ok(SearchResult)` - If the package is found, returns a `SearchResult` containing the package details.
If a match is found; drop "a"

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +/// One of the searching methods which provided by oma.
Drop this line.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +/// This searching method will be sorted based on string matching similarity (score).
strsim: Sort search results based on...

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +/// Based on `strsim`
Drop this line.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +    /// The Cache from oma-apt (rust-apt), which contains the summary of all the apt operations.
See above.

2025-02-06 06:45 UTC, MingcongBai commented on oma-pm/src/search.rs
> +/// One of the searching methods which provided by oma.
Drop this line.

2025-02-10 08:16 UTC, wxiwnd commented on oma-pm/src/apt.rs
> +    /// The Tokio runtime used for asynchronous operations.
I removed it since it is not so necessary.

2025-02-10 08:46 UTC, wxiwnd commented on oma-pm/src/lib.rs
> +//! - `AptErrors`: Error definitions from `oma_apt` crate.
y

2025-02-11 03:05 UTC, MingcongBai approved these changes

2025-02-11 09:14 UTC, MingcongBai approved these changes

2025-02-11 09:15 UTC, merged